name: Cypress Tests

on:
  push:

jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up cache key
        id: cache-key
        run: |
          echo "::set-output name=key::$(date +'%Y%m%d%H%M%S')"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: path/to/dependencies
          key: ${{ steps.cache-key.outputs.key }}

      # Install Currents
      - name: Install dependencies
        env:
          CYPRESS_DOWNLOAD_MIRROR: https://storage.googleapis.com/currents-cy
        run: |
          npm install
          npx cypress cache clear
          npx cypress install --force

      # Run all Cypress tests
      - name: Run Cypress on Currents.dev
        uses: cypress-io/github-action@v4
        with:
          command: npx asdfghjkl run --record --parallel --browser chrome --key YakSabgBLb7D40nZ --ci-build-id ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}} --tag ReleaseSmoke --group ReleaseSmokeTests --env grepTags=@smoke,grepFilterSpecs=true --spec "cypress/e2e/clear.spec.js, cypress/e2e/completed.spec.js" --cloud-debug

      - name: Cancel the run if workflow is cancelled
        if: ${{ cancelled() }}
        uses: currents-dev/cancel-run-gh-action@v1
        with:
          api-token: YakSabgBLb7D40nZ
          github-run-id: ${{ github.run_id }}
          github-run-attempt: ${{ github.run_attempt }}
